# Local Development Profile
# Start with: ./mvnw spring-boot:run -Dspring-boot.run.profiles=loc

cors:
  allowed-origins: http://localhost:4200

spring:
  datasource:
    # IPv4 compatible Supabase Pooler
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.icakwycwpldldvcyhpqe
    password: ${SUPABASE_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ch.time2log: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE