spring:
  application:
    name: admin-time2log-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_AUTH_URL}

supabase:
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

server:
  port: 9080
  shutdown: graceful

logging:
  level:
    root: INFO
    ch.time2log: INFO