spring:
  application:
    name: admin-time2log-backend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_AUTH_URL}

supabase:
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}

server:
  port: 9080
  shutdown: graceful

logging:
  level:
    root: INFO
    ch.time2log: INFO
    org.hibernate.SQL: ${SQL_LOG_LEVEL:INFO}