cors:
  allowed-origins: http://localhost:4200

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:54321/auth/v1

supabase:
  url: http://127.0.0.1:54321
  anon-key: sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH

logging:
  level:
    ch.time2log: DEBUG
    reactor.netty.http.client: DEBUG
